---
# tasks file for cassandra
- include_tasks: install_jdk_deb.yml
  when: ansible_facts['os_family'] == "Debian"
- include_tasks: install_jdk_redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- include_tasks: install_cassandra_deb.yml
  when: ansible_facts['os_family'] == "Debian"
- include_tasks: install_cassandra_redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

