---
# tasks file for cassandra-2

- include_tasks: temp_dir.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: install_jdk_deb.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: install_cassandra_deb.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: check_installation.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: remove_dir.yml
  when: ansible_facts['os_family'] == "Debian"

#- include_tasks: change_config.yml
 # when: ansible_facts['os_family'] == "Debian"
